---
title: "PA1_template.Rmd"
author: "abhibhaku"
date: "April 22, 2018"
output: html_document
---


## Loading and preprocessing the data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("D:/ISB Co 2018/Coursera/Data Science Specialization/Reproducible Research/Week 2/Project 1")

actv1 <- read.csv("activity.csv")
str(actv1)

library(dplyr)
library(zoo)

actv1 <- mutate(actv1, date = as.Date(as.character(date), "%Y-%m-%d"))

is.regular(actv1$date)
unique(actv1$date)

```

## What is mean total number of steps taken per day?

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

t_steps1 <- aggregate(steps~date,data=actv1,sum,na.rm = TRUE)
names(t_steps1) <- c("date","sum of steps")
hist(t_steps1$`sum of steps`, main = "histogram of the total steps taken each day", xlab = "steps each day", breaks = 20, col = "red")

mean(t_steps1$`sum of steps`)
median(t_steps1$`sum of steps`)

```

## What is the average daily activity pattern?

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

i_steps1 <- aggregate(steps~interval,data=actv1,mean,na.rm = TRUE)
names(i_steps1) <- c("interval", "mean")
plot(i_steps1,type="l")

i_steps1$interval[which.max(i_steps1$mean)]

```
## Imputing missing values

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

sum(is.na(actv1))

actv2 <- actv1
actv2$steps[is.na(actv2$steps)] <- mean(na.omit(actv2$steps))
actv2$date <- as.Date(actv2$date,format = "%Y-%m-%d")

t_steps2 <- aggregate(steps~date,data=actv2,sum,na.rm = TRUE)
names(t_steps2) <- c("date","sum of steps")
hist(t_steps2$`sum of steps`, main = "histogram of the total steps taken each day", xlab = "steps each day", breaks = 20, col = "red")

mean(t_steps2$`sum of steps`)
median(t_steps2$`sum of steps`)

```

## Are there differences in activity patterns between weekdays and weekends?

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)

# write a fucntion to check if date corresponnds to weekday or weekend

whatday <- function(d){
  c <- weekdays(d)
  ifelse (c=="Saturday"|c=="Sunday","weekend","weekday")
}

e <- sapply(actv2$date,whatday)
actv2$wkday <- as.factor(e)

# panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis)

library(lattice)
actv_wk <- aggregate(steps ~ wkday+interval, data=actv2, FUN=mean)
xyplot(steps ~ interval | factor(wkday),layout = c(1, 2), xlab="Interval", ylab="No of steps", type="l", lty=1, data=actv_wk)

```

